const TabSpace = ({ size = 4 }) => <span style={{ marginLeft: `${size}ch` }}></span>;

export const scientificDiscoveriesCategoryTopics: Record<string, { header: string; links: { id: number; title: string; category: string; topic: string , description?: React.ReactNode}[]; }> = {
  "physics-space": {
  header: "Physics & Space",
  links: [
    { id: 1, title: "Law of Gravity – Isaac Newton (1687)", category: "physics-space", topic: "law-of-gravity",
      description: <p><TabSpace size={5}/>- In 1687, Sir Isaac Newton published his groundbreaking work <i>Philosophiæ Naturalis Principia Mathematica</i>, in which he formulated the Law of Universal Gravitation, one of the most fundamental principles in physics. Newton's law states that every mass in the universe attracts every other mass with a force that is directly proportional to the product of their masses and inversely proportional to the square of the distance between their centers. Mathematically, this is expressed as F = G (m₁m₂) / r², where F is the gravitational force, G is the gravitational constant, m₁ and m₂ are the masses of two objects, and r is the distance between them. This law explained why objects fall to the ground, why planets orbit the Sun, and why the Moon stays in orbit around Earth. Newton's insights unified celestial and terrestrial mechanics, showing that the same force that makes an apple fall from a tree also governs the motion of planets and stars. His work built upon previous studies by scientists like Galileo Galilei and Johannes Kepler, particularly Kepler’s laws of planetary motion, which Newton derived from his theory of gravity. The inverse-square nature of gravitational attraction explained why planetary orbits are elliptical rather than circular. Despite its success, Newton's theory was later refined by Albert Einstein’s General Theory of Relativity (1915), which provided a deeper understanding of gravity as the curvature of spacetime rather than a simple force between masses. However, Newton's Law of Universal Gravitation remains highly useful in most practical applications, including engineering, space travel, and predicting planetary movements, proving to be one of the most significant scientific discoveries in history.</p>
    },
    { id: 2, title: "Theory of Relativity – Albert Einstein (1905)", category: "physics-space", topic: "theory-of-relativity", 
      description: <p><TabSpace size={5}/>- In 1905, Albert Einstein published his Special Theory of Relativity, fundamentally changing the understanding of space, time, and motion. This theory introduced two key postulates: first, that the laws of physics are the same for all observers in uniform motion, and second, that the speed of light in a vacuum is constant regardless of an observer’s motion. One of its most profound consequences is time dilation, where time slows down for an object moving close to the speed of light, and length contraction, where an object's length shortens in the direction of motion. The theory also led to the famous equation E = mc², which reveals that energy and mass are interchangeable, laying the foundation for nuclear power and atomic energy. In 1915, Einstein expanded on these ideas with the General Theory of Relativity, redefining gravity as the curvature of spacetime caused by massive objects rather than a force acting at a distance. This theory successfully explained the anomalous orbit of Mercury and predicted the bending of light around massive bodies, known as gravitational lensing, which was later confirmed through astronomical observations. General Relativity also provided the basis for modern cosmology, predicting phenomena such as black holes and gravitational waves, both of which have been experimentally verified in the 21st century. Einstein’s theories transformed physics, influencing technologies like GPS systems, particle accelerators, and space exploration, making the Theory of Relativity one of the most significant scientific achievements in history.</p>
    },
    { id: 3, title: "Quantum Mechanics – Niels Bohr (1922)", category: "physics-space", topic: "quantum-mechanics", 
      description: <p><TabSpace size={5}/>- In 1922, Niels Bohr made significant contributions to the development of quantum mechanics, particularly through his model of the atom and his understanding of electron behavior. Bohr's atomic model introduced the concept of quantized energy levels, where electrons orbit the nucleus at specific distances and can transition between these orbits by absorbing or emitting energy. This model explained phenomena such as atomic spectra and laid the foundation for modern atomic theory. Bohr's work was instrumental in developing the Copenhagen interpretation of quantum mechanics, which posits that the behavior of particles is inherently probabilistic and that physical systems exist in superpositions of states until measured. His contributions to quantum theory earned him the Nobel Prize in Physics in 1922 and influenced subsequent advancements in quantum mechanics, including the development of quantum field theory and quantum computing.</p>
    },
    { id: 4, title: "Higgs Boson – Peter Higgs (1964)", category: "physics-space", topic: "higgs-boson", 
      description: <p><TabSpace size={5}/>- In 1964, Peter Higgs, along with other physicists, proposed the existence of the Higgs boson, a fundamental particle that explains how other particles acquire mass. This idea was part of the Higgs mechanism, a theoretical framework within the Standard Model of particle physics. The Higgs field, an invisible energy field that permeates the universe, interacts with elementary particles, giving them mass through the Higgs boson. Without this mechanism, fundamental particles like electrons and quarks would remain massless, making the formation of atoms and, ultimately, the universe as we know it impossible. For decades, the Higgs boson remained a theoretical prediction until its discovery in 2012 at CERN’s Large Hadron Collider (LHC). This discovery confirmed the existence of the Higgs field and validated the Standard Model, marking one of the greatest achievements in modern physics. The Higgs boson is often referred to as the 'God particle' due to its fundamental role in the structure of the universe. Its discovery has profound implications for understanding the fundamental forces of nature, the evolution of the universe, and potential new physics beyond the Standard Model, including theories related to dark matter and supersymmetry. Peter Higgs was awarded the Nobel Prize in Physics in 2013 for his pioneering work, cementing his legacy as one of the most influential physicists of the 20th century.</p>
    },
    { id: 5, title: "Dark Matter – Fritz Zwicky (1933)", category: "physics-space", topic: "dark-matter", 
      description: <p><TabSpace size={5}/>- In 1933, Swiss astronomer Fritz Zwicky first proposed the existence of dark matter while studying the Coma Cluster, a massive collection of galaxies. He observed that the galaxies within the cluster were moving at speeds far greater than expected based on the visible mass alone. Using the virial theorem, Zwicky calculated that the total mass required to keep the galaxies gravitationally bound was much higher than what could be accounted for by the observable stars and gas. He coined the term 'dunkle Materie' (dark matter) to describe this unseen mass, suggesting that an invisible substance must be exerting gravitational influence. Despite initial skepticism, later observations, including galaxy rotation curves studied by Vera Rubin in the 1970s, confirmed that galaxies spin faster at their edges than predicted by Newtonian mechanics, further supporting the existence of dark matter. Modern astrophysics estimates that dark matter makes up about 27% of the universe, yet it does not emit, absorb, or reflect light, making it extremely difficult to detect directly. Scientists hypothesize that dark matter consists of unknown particles such as Weakly Interacting Massive Particles (WIMPs) or axions, though its true nature remains one of the biggest mysteries in cosmology. The study of dark matter is crucial for understanding the large-scale structure of the universe, galaxy formation, and the evolution of cosmic expansion, making Zwicky’s pioneering discovery a cornerstone of modern astrophysics.</p>
    },
    { id: 6, title: "Expansion of the Universe – Edwin Hubble (1929)", category: "physics-space", topic: "expansion-of-the-universe", 
      description: <p><TabSpace size={5}/>- In 1929, American astronomer Edwin Hubble provided groundbreaking evidence that the universe is expanding, fundamentally reshaping modern cosmology. By analyzing the redshift of light from distant galaxies, Hubble discovered that galaxies were moving away from Earth, with their velocities increasing in proportion to their distance. This observation led to the formulation of Hubble’s Law, expressed as v = H₀d, where v is the recession velocity of a galaxy, H₀ is Hubble’s constant, and d is the galaxy’s distance from Earth. This discovery provided strong support for the Big Bang theory, which suggests that the universe originated from a singularity and has been expanding ever since. Hubble’s findings overturned the previously accepted static universe model and laid the foundation for modern cosmology. His work was later refined by improved measurements of Hubble’s constant, cosmic microwave background radiation, and large-scale structure surveys. The expansion of the universe also led to the discovery of dark energy, an unknown force driving the accelerated expansion of the cosmos. Hubble’s contributions revolutionized our understanding of the universe’s origin, structure, and ultimate fate, making his work one of the most significant achievements in astronomy. The Hubble Space Telescope, launched in 1990, was named in his honor, continuing his legacy by exploring the depths of the universe and uncovering new cosmic phenomena.</p>
    },
    { id: 7, title: "Gravitational Waves – LIGO Team (2015)", category: "physics-space", topic: "gravitational-waves", 
      description: <p><TabSpace size={5}/>- In 2015, the LIGO team made a groundbreaking discovery by directly detecting gravitational waves, a phenomenon predicted by Albert Einstein’s General Theory of Relativity a century earlier. Gravitational waves are ripples in spacetime caused by the acceleration of massive objects, such as merging black holes or neutron stars. The detection of these waves confirmed Einstein’s prediction and opened a new era in astronomy, allowing scientists to observe cosmic events that were previously undetectable. The LIGO team’s achievement has profound implications for our understanding of the universe, providing insights into the nature of gravity, the behavior of black holes, and the dynamics of the early universe. The discovery also paved the way for multi-messenger astronomy, which combines gravitational wave observations with electromagnetic signals to gain a more comprehensive understanding of astrophysical phenomena. The LIGO team's work was recognized with the Nobel Prize in Physics in 2017, marking a significant milestone in the field of astrophysics.</p>
    },
  ],
},
  "biology-medicine": {
    header: "Biology & Medicine",
    links: [
      { id: 1, title: "Discovery of DNA – James Watson & Francis Crick (1953)", category: "biology-medicine", topic: "discovery-of-dna", 
        description: <p><TabSpace size={5}/>- In 1953, James Watson and Francis Crick discovered the double-helix structure of DNA, revolutionizing the field of genetics and molecular biology. Building upon the X-ray diffraction data produced by Rosalind Franklin and Maurice Wilkins, Watson and Crick proposed that DNA is composed of two strands coiled around each other, forming a helical shape. These strands are made up of nucleotide bases—adenine (A), thymine (T), cytosine (C), and guanine (G)—which pair specifically (A with T, and C with G) through hydrogen bonds. This complementary base pairing mechanism explained how genetic information is stored and replicated with remarkable accuracy. Their discovery provided the foundation for understanding how genetic instructions are passed from one generation to the next, influencing fields such as medicine, biotechnology, and forensic science. The double-helix model also helped pave the way for advancements like DNA sequencing, genetic engineering, and the Human Genome Project. In 1962, Watson, Crick, and Wilkins were awarded the Nobel Prize in Physiology or Medicine for their contributions, though Franklin’s crucial role was largely unrecognized at the time. The discovery of DNA’s structure remains one of the most significant breakthroughs in science, shaping modern biology and deepening our understanding of life at the molecular level.</p>

      },
      { id: 2, title: "Theory of Evolution – Charles Darwin (1859)", category: "biology-medicine", topic: "theory-of-evolution", 
        description: <p><TabSpace size={5}/>- In 1859, Charles Darwin published *On the Origin of Species*, introducing the Theory of Evolution by Natural Selection, one of the most influential scientific ideas in history. Darwin proposed that all species of life have evolved over time from common ancestors through a gradual process driven by natural selection. In this mechanism, individuals with traits that provide a survival or reproductive advantage are more likely to pass those traits on to their offspring, leading to the adaptation and diversification of species over generations. His extensive observations, particularly from his voyage on the HMS Beagle, provided compelling evidence for evolution, including variations in finch species on the Galápagos Islands that adapted to different ecological niches. Darwin’s theory challenged traditional views on the origins of life and laid the foundation for modern biology, genetics, and paleontology. Despite initial controversy, evolutionary theory has been overwhelmingly supported by discoveries in genetics, fossil records, and molecular biology. The integration of Mendelian genetics with Darwin’s ideas led to the Modern Synthesis, further solidifying evolution as the unifying principle of life sciences. Today, the Theory of Evolution continues to shape our understanding of biodiversity, medicine, and conservation, proving to be one of the most profound scientific contributions of all time.</p>

      },
      { id: 3, title: "Germ Theory – Louis Pasteur (1861)", category: "biology-medicine", topic: "germ-theory", 
        description: <p><TabSpace size={5}/>- In 1861, Louis Pasteur formulated the Germ Theory of Disease, fundamentally transforming medicine and microbiology. Pasteur's experiments demonstrated that microorganisms, rather than spontaneous generation, were responsible for fermentation and infectious diseases. Through his famous swan-neck flask experiment, he proved that sterilized liquids remained free of microbial growth unless exposed to contaminated air, debunking the long-held theory of spontaneous generation. His discoveries led to the development of pasteurization, a process that kills harmful microbes in food and beverages, significantly improving public health. Germ Theory provided the scientific basis for antiseptic techniques, vaccination, and modern microbiology, paving the way for advancements by figures such as Joseph Lister and Robert Koch. Pasteur’s work also contributed to the understanding of immunity and led to the creation of vaccines for rabies and anthrax. His groundbreaking research revolutionized disease prevention and treatment, reducing mortality rates and extending human life expectancy. Today, Germ Theory remains a cornerstone of medicine, guiding infection control, hygiene practices, and antibiotic development, making Pasteur’s contributions some of the most impactful in the history of science.</p>

      },
      { id: 4, title: "DNA Structure – Rosalind Franklin (1952)", category: "biology-medicine", topic: "dna-structure", 
        description: <p><TabSpace size={5}/>- In 1952, Rosalind Franklin made a crucial contribution to the discovery of DNA’s double-helix structure through her pioneering work with X-ray diffraction. Using advanced imaging techniques, Franklin captured the famous 'Photo 51,' which provided key evidence that DNA had a helical structure. Her meticulous research revealed the molecule’s dimensions and suggested a phosphate backbone on the outside with nitrogenous bases paired on the inside. Although her data was shared without her direct knowledge with James Watson and Francis Crick, it played an essential role in their 1953 model of the DNA double helix. Despite her groundbreaking work, Franklin did not receive the recognition she deserved during her lifetime, as the 1962 Nobel Prize in Physiology or Medicine was awarded to Watson, Crick, and Maurice Wilkins. However, her contributions have since been widely acknowledged, and she is now celebrated as a pioneer in molecular biology. Franklin’s work not only helped unravel the fundamental blueprint of life but also laid the foundation for modern genetics, biotechnology, and medical advancements, making her legacy one of the most significant in the history of science.</p>

      },
      { id: 5, title: "CRISPR Gene Editing – Jennifer Doudna & Emmanuelle Charpentier (2012)", category: "biology-medicine", topic: "crispr-gene-editing", 
        description: <p><TabSpace size={5}/>- In 2012, Jennifer Doudna and Emmanuelle Charpentier revolutionized genetic engineering by developing CRISPR-Cas9, a powerful gene-editing technology that allows scientists to precisely modify DNA. Inspired by the natural immune system of bacteria, CRISPR (Clustered Regularly Interspaced Short Palindromic Repeats) works by using a guide RNA to direct the Cas9 enzyme to a specific DNA sequence, where it makes a precise cut, enabling the removal, addition, or alteration of genetic material. This breakthrough has transformed molecular biology, enabling rapid advancements in medicine, agriculture, and biotechnology. CRISPR holds the potential to cure genetic diseases, develop more resilient crops, and even combat viral infections. However, its ethical implications, particularly regarding human germline editing, have sparked significant debate. In recognition of their groundbreaking discovery, Doudna and Charpentier were awarded the 2020 Nobel Prize in Chemistry, making history as the first all-female team to receive a Nobel Prize in the sciences. CRISPR continues to evolve, with ongoing research exploring new applications and refining its precision, ensuring its role as one of the most significant scientific innovations of the 21st century.</p>

      },
    ],
  },
  "chemistry": {
    header: "Chemistry",
    links: [
      { id: 1, title: "Discovery of Oxygen – Joseph Priestley (1774)", category: "chemistry", topic: "discovery-of-oxygen",
        description: <p><TabSpace size={5}/>- In 1774, Joseph Priestley discovered oxygen by heating mercuric oxide and collecting the gas released. He called it "dephlogisticated air," noting that it supported combustion and respiration more effectively than regular air. This discovery was crucial in advancing chemistry and led to a better understanding of gases and their role in life and combustion.</p>

      },
      { id: 2, title: "Discovery of Nitrogen – Daniel Rutherford (1772)", category: "chemistry", topic: "discovery-of-nitrogen",
        description: <p><TabSpace size={5}/>- In 1772, Daniel Rutherford discovered nitrogen by removing oxygen and carbon dioxide from air, leaving behind an unreactive gas. He called it "noxious air" since it could not support combustion or respiration. This discovery helped establish the concept of inert gases and played a key role in the development of modern chemistry.</p>

      },
      { id: 3, title: "Periodic Table – Dmitri Mendeleev (1869)", category: "chemistry", topic: "periodic-table",
        description: <p><TabSpace size={5}/>- In 1869, Dmitri Mendeleev developed the periodic table, organizing elements based on atomic weight and chemical properties. His arrangement revealed periodic trends and even predicted the existence of undiscovered elements. Mendeleev's work laid the foundation for modern chemistry, enabling scientists to understand elemental relationships and properties.</p>

      },
      { id: 4, title: "Discovery of Hydrogen – Henry Cavendish (1766)", category: "chemistry", topic: "discovery-of-hydrogen",
        description: <p><TabSpace size={5}/>- In 1766, Henry Cavendish discovered hydrogen by reacting metals with acids, producing a flammable gas he called "inflammable air." He found that it was lighter than air and, when burned, produced water. This discovery was crucial in understanding elemental gases and later contributed to the identification of water’s composition.</p>

      },
      { id: 5, title: "Radioactivity – Marie Curie (1898)", category: "chemistry", topic: "radioactivity",
        description: <p><TabSpace size={5}/>- In 1898, Marie Curie, along with her husband Pierre Curie, discovered the radioactive elements polonium and radium. She coined the term "radioactivity" and pioneered research into its properties and applications. Her groundbreaking work laid the foundation for nuclear physics and medical advancements, including radiation therapy for cancer treatment.</p>

      },
    ],
  },
  "earth-environmental-science": {
    header: "Earth & Environmental Science",
    links: [
      { id: 1, title: "Plate Tectonics – Alfred Wegener (1912)", category: "earth-environmental-science", topic: "plate-tectonics",
        description: <p><TabSpace size={5}/>- In 1912, Alfred Wegener proposed the theory of continental drift, suggesting that Earth's continents were once a single landmass (Pangaea) that gradually drifted apart. His idea, later refined into plate tectonics, explained geological phenomena like earthquakes, mountain formation, and oceanic trenches. Though initially controversial, his theory became a cornerstone of modern geology.</p>

      },
      { id: 2, title: "Continental Drift – Alfred Wegener (1912)", category: "earth-environmental-science", topic: "continental-drift",
        description: <p><TabSpace size={5}/>- In 1896, Svante Arrhenius proposed that carbon dioxide (CO₂) in the atmosphere influences Earth's temperature through the greenhouse effect. He calculated that increased CO₂ levels from burning fossil fuels could lead to global warming. His work laid the foundation for modern climate science and our understanding of human impact on climate change.</p>

      },
      { id: 3, title: "Global Climate Change – Svante Arrhenius (1896)", category: "earth-environmental-science", topic: "global-climate-change",
        description: <p><TabSpace size={5}/>- In 1896, Svante Arrhenius proposed that carbon dioxide (CO₂) in the atmosphere traps heat, leading to the greenhouse effect. He calculated that increasing CO₂ levels from human activities, such as burning fossil fuels, could cause global warming. His research was the first to quantify the relationship between CO₂ and temperature, forming the foundation of modern climate science.</p>

      },
      { id: 4, title: "Fossil Record – Charles Darwin (1859)", category: "earth-environmental-science", topic: "fossil-record",
        description: <p><TabSpace size={5}/>- In 1859, Charles Darwin used the fossil record as evidence for his theory of evolution by natural selection. Fossils provided a historical record of life, showing gradual changes in species over time. This supported the idea that organisms evolved from common ancestors, reinforcing the concept of descent with modification in his groundbreaking work, *On the Origin of Species*.</p>

      },
    ],
  },
  "technology-computing": {
    header: "Technology & Computing",
    links: [
      { id: 1, title: "Transistor – John Bardeen, Walter Brattain, William Shockley (1947)", category: "technology-computing", topic: "transistor", 
        description: <p><TabSpace size={5}/>- In 1947, John Bardeen, Walter Brattain, and William Shockley invented the transistor at Bell Labs. This semiconductor device could amplify and switch electronic signals, revolutionizing technology by replacing bulky vacuum tubes. The transistor became the foundation of modern electronics, enabling the development of computers, communication systems, and countless digital devices.</p>

      },
      { id: 2, title: "Microcomputer – Ed Roberts (1975)", category: "technology-computing", topic: "microcomputer", 
        description: <p><TabSpace size={5}/>- In 1975, Ed Roberts developed the Altair 8800, the first commercially successful microcomputer. Featuring the Intel 8080 processor, it sparked the personal computing revolution by making computers accessible to hobbyists and innovators. The Altair 8800 inspired future advancements, leading to the rise of companies like Microsoft and the development of modern personal computers.</p>

      },
      { id: 3, title: "Personal Computer – Steve Jobs & Steve Wozniak (1976)", category: "technology-computing", topic: "personal-computer", 
        description: <p><TabSpace size={5}/>- In 1976, Steve Jobs and Steve Wozniak introduced the Apple I, one of the first personal computers designed for individual use. Unlike earlier microcomputers, it featured a fully assembled circuit board, making it more user-friendly. This innovation laid the foundation for the personal computing revolution, leading to the development of the Apple II and shaping the future of modern technology.</p>

      },
      { id: 4, title: "Internet – Tim Berners-Lee (1990)", category: "technology-computing", topic: "internet", 
        description: <p><TabSpace size={5}/>- In 1990, Tim Berners-Lee developed the World Wide Web, revolutionizing global communication. He created key components like HTML, URLs, and HTTP, enabling users to access and share information easily. His invention transformed the internet into a user-friendly platform, laying the foundation for modern websites, online services, and the digital age.</p>

      },
      { id: 5, title: "Smartphones – IBM Simon (1992)", category: "technology-computing", topic: "smartphones", 
        description: <p><TabSpace size={5}/>- In 1992, IBM introduced the Simon Personal Communicator, the first device to combine mobile phone capabilities with PDA features. It featured a touchscreen, email, and apps, making it a precursor to modern smartphones. Although limited in adoption, the IBM Simon laid the groundwork for future advancements in mobile technology.</p>

      },
      { id: 6, title: "Smartwatches – Pebble (2012)", category: "technology-computing", topic: "smartwatches", 
        description: <p><TabSpace size={5}/>- In 2012, Pebble launched one of the first modern smartwatches, pioneering wearable technology with smartphone connectivity. Featuring an e-paper display, notifications, and customizable apps, it set the stage for the smartwatch industry. Pebble’s success influenced major tech companies, leading to the development of advanced smartwatches like the Apple Watch and Samsung Gear.</p>

      },
    ],
  },
};